---
- name: "Configure Proxy for DNF."
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: "http://{{ proxy_package_proxy_server }}:{{ proxy_package_proxy_port }}"
    state: "{{ proxy_state }}"
    owner: root
    group: root
    mode: 0644

- name: "Configure Proxy User for DNF."
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy_username
    value: "{{ proxy_package_proxy_username }}"
    state: "{{ username_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: "Configure Proxy Password for DNF."
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy_password
    value: "{{ proxy_package_proxy_password }}"
    state: "{{ password_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
