---
- name: "Configure Proxy for YUM."
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy
    value: "http://{{ proxy_package_proxy_server }}:{{ proxy_package_proxy_port }}"
    state: "{{ proxy_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: "Configure Proxy User for YUM."
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy_username
    state: "{{ username_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: "Configure Proxy Password for YUM."
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy_password
    value: "{{ proxy_package_proxy_password }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
    state: "{{ password_state }}"
